server: 
  port: 9005

rocketmq:
  producer:
    group: test-group
    namesrvAddr: 192.168.133.130:9876
    instanceName: testProducer
    maxMessageSize: 131072
    sendMsgTimeout: 10000
    retryTimes: 3
    defaultTopicQueueNums: 10
  consumer:
    namesrvAddr: 192.168.133.130:9876
    consumeThreadMin: 20
    consumeThreadMax: 64
